### ISSUE TITLE
Avoiding `__invoke()` for route handlers

### ISSUE THREAD

**Issue by GarrettAlbright** [kevinsmith/no-framework#10]
I don't like the idea of using the `__invoke()` magic method for route handlers as this tutorial suggests because, weirdness of calling a class as a function aside, wouldn't this approach mean I'd need to create a new class for every single route handler I want to create?

Is there a way that I can specify a class method to be invoked instead, so that I could bundle together related route handlers into classes? I've figured out you can pass the string 'ClassName::methodName' to FastRoute, but that only works if the method is static, which is far from ideal.

**Comment by kevinsmith** [comment]
Yup, these are Actions (sometimes called single-action Controllers), and the idea is to separate route handlers because the handling of each route is necessarily a distinct responsibility. They're natively supported by [middlewares/request-handler](https://github.com/middlewares/request-handler) which is nice for the sake of this tutorial, but that doesn't mean you have to use this particular routing setup.

You could swap it out for something like The PHP League's Route, which [supports the Controller::method definition](https://route.thephpleague.com/5.x/controllers/) you're looking for.

Hope this helps!
